@baseUrl = http://localhost:3000




POST {{baseUrl}}/api/projects
Content-Type: application/json

{
    "title": "test1",
    "description": "Description1",
    "availability": "true",
    "user_id": "2"
}
