@baseUrl = http://localhost:3000
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}


# @name register
POST {{baseUrl}}/signin
content-type: application/json

{
    "email": "jo@olck.io",
    "password": "secret",
    "name": "Mangeot",
    "firstname": "Pierre",
    "pseudo": "Pierrot",
    "description": "Lorem ipsum blabla",
    "availability": true,
    "tags": [
        {
          "id": 2,
          "name": "Javascript"
        },
        {
          "id": 3,
          "name": "HTML"
        },
        {
          "id": 6,
          "name": "SQL"
        }
      ]
}

###
# @name login
POST {{baseUrl}}/login
content-type: application/json

{
    "email": "pano@ramix.ga",
    "password": "secret"
}

###

GET {{baseUrl}}/api/projects/1
content-type: application/json
Authorization: Bearer 

###

PUT {{baseUrl}}/api/users/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoicGFub0ByYW1peC5nYSIsImlkIjozfSwiaWF0IjoxNjg3MTA1MDA1LCJleHAiOjE2ODcxNTkwMDV9.Dj00J9H3usjUDzPwxLPQXeV6aMstYi9XD_9Iri7aSAY

{
    "name": "Danglot",
    "firstname": "Clément",
    "pseudo": "Panoramix",
    "email": "pano@ramix.ga",
    "description": "Grande hutte à la sortie du village",
    "availability": true,
    "projects": [
      {
        "id": 1,
        "title": "Biscoc O",
        "description": "Lorem ipsum blabla",
        "availability": true
      }
    ],
    "tags": [
      {
        "id": 1,
        "name": "Java"
      },
      {
        "id": 4,
        "name": "HTML"
      },
      {
        "id": 6,
        "name": "SQL"
      }
    ]
}


###
POST {{baseUrl}}/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
