@baseUrl = http://localhost:3000
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}


# @name register
POST {{baseUrl}}/register
content-type: application/json

{
    "email": "benji@oclock.io",
    "password": "secret"
}

###
# @name login
POST {{baseUrl}}/login
content-type: application/json

{
    "email": "amon@bofis.eg",
    "password": "secret"
}

###

GET {{baseUrl}}/api/book
content-type: application/json
Authorization: Bearer {{accessToken}}

###

PUT {{baseUrl}}/api/projects/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiYW1vbkBib2Zpcy5lZyIsImlkIjoyfSwiaWF0IjoxNjg2ODMzNTczLCJleHAiOjE2ODY4MzQ0NzN9.PAEtqYPNReD_RXmU9W1MhOXfmyZasmkNzxCteQhK9eA

{
  "title": "Biscoc 5",
  "description": "Lorem ipsum blabla",
  "availibility": false,
  "user_id": 2,
  "tags": [1, 3, 4],
  "users": [
    {
      "id": 1,
      "name": "Gandji"
    },
    {
      "id": 2,
      "name": "Mangeot"
    },
    {
      "id": 3,
      "name": "Danglot"
    }
  ]
}

###
POST {{baseUrl}}/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
