@baseUrl = http://localhost:3000
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}


# @name register
PUT {{baseUrl}}/api/users/12
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiYmlwb3VAb2xjay5pbyIsImlkIjoxMiwibG9nZ2VkIjp0cnVlLCJwc2V1ZG8iOiJQYXQifSwiaWF0IjoxNjg3MTc1NTQzLCJleHAiOjE2ODcyMjk1NDN9.U3ZH4tpc9GFKNvhFB1cUZpFbY7EtnSjCZQqaVBqplWw

{
    "email": "bipou@olck.io",
    "password": "secret",
    "name": "Manot",
    "firstname": "Pierre",
    "pseudo": "Pat",
    "description": "Loem ipsum blabla",
    "availability": true,
    "tags": [ 1, 4 ]
}

###
# @name login
POST {{baseUrl}}/login
content-type: application/json

{
    "email": "numero@bis.eg",
    "password": "secret"
}

###

GET {{baseUrl}}/api/projects/1
content-type: application/json
Authorization: Bearer 

###

PUT {{baseUrl}}/api/projects/17
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoibnVtZXJvQGJpcy5lZyIsImlkIjoxfSwiaWF0IjoxNjg3MzUwNDg0LCJleHAiOjE2ODc0MDQ0ODR9.86xyi2N52fOdajcDh_quUxNzGM8QV-YvbTTrC4KlrQU

{
  "title": "Blabla",
  "description": "Lor5um blabla",
  "availability": true,
  "user_id": 1,
  "tags": "[ 2, 1, 3 ]"
}

###

DELETE {{baseUrl}}/api/projects/17/user/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoibnVtZXJvQGJpcy5lZyIsImlkIjoxfSwiaWF0IjoxNjg3MjQ4NzMwLCJleHAiOjE2ODczMDI3MzB9.65L3LnhFd7q1PzHg3o85YP_kCiSLSVBWQVSqPQVFc2s


###

POST {{baseUrl}}/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoibnVtZXJvQGJpcy5lZyIsImlkIjoxfSwiaWF0IjoxNjg3MjQ4NzMwLCJleHAiOjE2ODczMDI3MzB9.65L3LnhFd7q1PzHg3o85YP_kCiSLSVBWQVSqPQVFc2s

{
  "title": "Blabla3",
  "description": "Lorem ipsum blabla",
  "availability": true,
  "user_id": 1,
  "tags": "[ 2, 1 ]"
}


###
POST {{baseUrl}}/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
