@baseUrl = http://localhost:3000
@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}


# @name login
POST {{baseUrl}}/login
content-type: application/json

{
    "email": "Charline.Prevost@gmail.com",
    "password": "secret"
}

###

# @name register
POST {{baseUrl}}/signin
content-type: application/json
Authorization: Bearer

{
  "name": "G",
  "firstname": "S",
  "email": "Eddie33@gmail.com",
  "pseudo": "Ata5",
  "password": "secret",
  "description": "Vieux loup de mer",
  "availability": true,
  "tags": [ 1, 2 ]
}

###

# @name getUsers
GET {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer 

###

# @name getOneUser
GET {{baseUrl}}/api/users/12
content-type: application/json
Authorization: Bearer 

###

# @name editUser
PUT {{baseUrl}}/api/users/5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiQ2hhcmxpbmUuUHJldm9zdEBnbWFpbC5jb20iLCJpZCI6NX0sImlhdCI6MTY4Nzc4MDczMCwiZXhwIjoxNjg3ODM0NzMwfQ._XQPL8YCwAiTZcpkl8NmrQUTxbdfkQoPSDsfnlnOniw

{
  "name": "E",
  "firstname": "Haddock",
  "email": "Charline.Prevost@gmail.com",
  "pseudo": "Boup",
  "password": "secret",
  "description": "Vieille louve de mer",
  "availability": true,
  "tags": [
    1,
    3,
    4
  ]
}

###

# @name deleteUser
DELETE {{baseUrl}}/api/users/1
content-type: application/json
Authorization: Bearer 

###

# @name getProjects
GET {{baseUrl}}/api/projects
content-type: application/json
Authorization: Bearer 

###

# @name getOneProject
GET {{baseUrl}}/api/projects/1
content-type: application/json
Authorization: Bearer 

###

# @name createProject
POST {{baseUrl}}/api/projects
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiQXVkZWxpbmUuQmxhbmNoYXJkNTdAZ21haWwuY29tIiwiaWQiOjJ9LCJpYXQiOjE2ODc3NzMyNjAsImV4cCI6MTY4NzgyNzI2MH0.ZAhIGfcJ3SvsqFwLulXkquNamcIJERt9cBNd2axxIDE

{
  "title": "Bisco98",
  "availability": false,
  "description": "Loremipsumblabla",
  "user_id": 2,
  "tags": [
    2,
    3,
    4
  ]
}

###

# @name editProject
PUT {{baseUrl}}/api/projects/43
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiQXVkZWxpbmUuQmxhbmNoYXJkNTdAZ21haWwuY29tIiwiaWQiOjJ9LCJpYXQiOjE2ODc3NzM4OTcsImV4cCI6MTY4NzgyNzg5N30.lLo17I7Ym1AW5BvzvEDaMEEyOaNeztQffC5x-1q381o

{
  "title": "Bisco97",
  "availability": true,
  "description": "Lorem ipsum blabla",
  "user_id": 2,
  "tags": [
    2,
    6,
    4
  ]
}

###

# @name deleteProject
DELETE {{baseUrl}}/api/projects/1
content-type: application/json
Authorization: Bearer 

###

# @name applyToProject
POST {{baseUrl}}/api/projects/1/user/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoicGFub0ByYW1peC5nYSIsImlkIjozfSwiaWF0IjoxNjg3NDI4NDYzLCJleHAiOjE2ODc0ODI0NjN9.rZSsmaEGXHmI1z8gcqxoZrSLDGykM_cKgYxUK89nNT8

###

# @name addUserToProject
PUT {{baseUrl}}/api/projects/1/user/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiY2FwdGFpbkBnbWFpbC5jb20iLCJpZCI6Mn0sImlhdCI6MTY4NzQyODEzMiwiZXhwIjoxNjg3NDgyMTMyfQ._XQgPEyfHOAOzBY-uXzYz_gSazIDA1jjbXrcYRL-mCc

###

# @name removeUserToProject
DELETE {{baseUrl}}/api/projects/1/user/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlwIjoiOjpmZmZmOjEyNy4wLjAuMSIsImVtYWlsIjoiY2FwdGFpbkBnbWFpbC5jb20iLCJpZCI6Mn0sImlhdCI6MTY4NzQyODEzMiwiZXhwIjoxNjg3NDgyMTMyfQ._XQgPEyfHOAOzBY-uXzYz_gSazIDA1jjbXrcYRL-mCc

###

POST {{baseUrl}}/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}
